DROP TABLE IF EXISTS to_do_entry CASCADE;

CREATE TABLE IF NOT EXISTS to_do_entry(
	entry_id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	entry VARCHAR(255) NOT NULL,
	start_time BIGINT NOT NULL,
	expected_duration BIGINT NOT NULL,
	PRIMARY KEY(entry_id)
)